### ISSUE TITLE
Tracing back to last line

### ISSUE THREAD

**Issue by wenhuizhang** [PrincetonUniversity/Coursera-SDN#31]
Hi, I was editing only the file /home/vagrant/netasm/netasm/examples/learning_switch_acl/learning_switch_acl_netasm.py , and got the following error trace back which does not make sense to me, and I did not change the line "return Policy(decls, code)". 
P.S. anyone know how to use P for communication, it showed up to me as "Homework
This resource section is not public for this course." . 

vagrant@coursera-sdn:~$ sudopy python /home/vagrant/pox/pox.py --no-openflow netasm.back_ends.soft_switch.datapath --address=127.0.0.1 --port=6633 --dpid=0000000000000001 --policy= --ports=s1-eth1,s1-eth2 --ctl_port=7791
POX 0.2.0 (carp) / Copyright 2011-2013 James McCauley, et al.
INFO:dp.00-00-00-00-00-01:Connecting to 127.0.0.1:6633
INFO:core:POX 0.2.0 (carp) is up.
INFO:dp.00-00-00-00-00-01:Connecting to 127.0.0.1:6633
INFO:dp.00-00-00-00-00-01:Connecting to 127.0.0.1:6633
INFO:dp.00-00-00-00-00-01:Connecting to 127.0.0.1:6633
INFO:dp.00-00-00-00-00-01:Connecting to 127.0.0.1:6633
INFO:dp.00-00-00-00-00-01:Connecting to 127.0.0.1:6633
INFO:dp.00-00-00-00-00-01:Connected to controller
ERROR:ControllerConnection(id=1):Exception handling SyntaxError
Traceback (most recent call last):
  File "/home/vagrant/pox/pox/datapaths/switch.py", line 1167, in read
    self.on_message_received(self, msg_obj)
  File "/home/vagrant/pox/pox/datapaths/switch.py", line 245, in rx_message
    h(msg, connection=connection)
  File "/home/vagrant/netasm/netasm/back_ends/soft_switch/datapath.py", line 472, in _rx_vendor
    self._handle_out_message(message, connection)
  File "/home/vagrant/netasm/netasm/back_ends/soft_switch/datapath.py", line 485, in _handle_out_message
    load_policy(self, policy_name)
  File "/home/vagrant/netasm/netasm/back_ends/soft_switch/datapath.py", line 173, in load_policy
    module = import_module(policy_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    **import**(name)
  File "/home/vagrant/netasm/netasm/examples/learning_switch_acl/learning_switch_acl_netasm.py", line 487
    return Policy(decls, code)
         ^
SyntaxError: invalid syntax

**Comment by feamster** [comment]
Github is for confirmed issues, not for debugging your assignment/setup.  Please post your questions to Piazza.  Closing this.
