### ISSUE TITLE
CustomTopo.py failed with ImportError

### ISSUE THREAD

**Issue by currand** [PrincetonUniversity/Coursera-SDN#33]
When attempting to run the pulled CustomTopo.py I get the following:

vagrant@coursera-sdn:~/Coursera-SDN/assignments/mininet-topology$ sudo ./CustomTopo.py
Traceback (most recent call last):
  File "./CustomTopo.py", line 13, in <module>
    from mininet.link import Link
  File "build/bdist.linux-x86_64/egg/mininet/link.py", line 29, in <module>
  File "build/bdist.linux-x86_64/egg/mininet/node.py", line 67, in <module>
ImportError: cannot import name Link

I've attempted to write a basic program that imports the TCLink class and I get the same issue.

**Comment by feamster** [comment]
This is a bug in your code, not a bug with the course examples.  Please post your questions to Piazza, not to the github issue tracker.
